@startuml "Diagrama de clases y relaciones"

title Diagrama de clases y relaciones
skinparam linetype ortho

'------------------- CLASES PRINCIPALES -------------------'

class Empresa {
    - nombre: String
    - codigo: String
    - informacionDePago: InformacionPago
    - empleados: List<Empleado>
    - clientes: List<Cliente>
    - proveedores: List<Proveedor>
    - bodegas: List<Bodega>
    - catalogo: Catalogo
    - cotizaciones: List<cotizacion>
    - comprobantes: List<ComprobantePago>
    - notasCorrecion: List<NotaCorrecion>
    - areasDeTrabajo: List<AreaDeTrabajo>
}

class Persona {
    - Nombre: String
    - TipoID: TipoID
    - Identificacion: String
    - FechaNacimiento: Date
    - Correo: String
    - Telefono: String
    - Direccion: String
}

enum TipoID {
    Cedula
    NIT
    Pasaporte
    PermisoDeTrabajo
}

class Empleado extends Persona {
    - contrato: Contrato
}

class Contrato {
    - FechaInicio: Date
    - FechaFinal: Date
    - SueldoBase: double
    - cargo: Cargo
    - horario: String
    - clausulas: List<String>
    - contratado: Empleado
    - contratante: Empresa
}
enum Cargo {
    Supervisor
    Mecanico
    Lavadero
}

class Cliente extends Persona {
    - vehiculos: List<Vehiculo>
    - turno: int
}

class Vehiculo {
    - marca: String
    - modelo: String
    - placa: String
    - tipo: String
    - color: String
    - planta: String
    - identificador: int
}

class Proveedor {
    - nombre: String
    - id: String
    - informacionPago: InformacionPago
    - comprobantes: List<ComprobantePago>
}

class InformacionPago {
    - metodos: List<MetodoPago>
    - direccion: String
    - telefono: String
    - email: String
    - cuentas: List<CuentaBancaria>
}

enum MetodoPago {
    Efectivo
    Transferencia
    Debito
    Credito
}

class CuentaBancaria {
    - numeroCuenta: String
    - banco: String
    - tipoCuenta: String
    - saldoActual: double
    - titular: String
}

class Catalogo {
    - categorias: List<Categoria>
    - productos: List<Producto>
    - servicios: List<Servicio>
    - empleadosQueHanMostrado: List<Empleado>
}

class Categoria {
    - codigo: String
    - nombre: String
    - icono: String
    - productos: List<Producto>
    - servicios: List<Servicio>
}

class Producto {
    - codigo: String
    - nombreProducto: String
    - Categoria: String
    - precio: double
    - stock: int
    - marca: String
    - precioDeCompra: double
    - disponibilidad: Boolean
    - alerta: int
    - codigoDelProveedor: String
}

class Servicio {
    - codigo: String
    - nombre: String
    - descripcion: String
    - precioDeVenta: double
    - porcentajeIva: double
    - valorCorrespondienteIVA: double
    - precioTotalConIva: double
    - descuento: double
    - precioTotal: double
    - vehiculo: Vehiculo
    - fechaInicio: Date
    - fechaFin: Date
    - funcionarios: List<Empleado>
    - imagen: String
    - disponibilidad: boolean
    - categoria: Categoria
}

class Bodega {
    - codigo: String
    - ubicacion: String
    - nombre: String
    - productos: List<Producto>
}

class AreaDeTrabajo {
    - idAreaDeTrabajo: String
    - nombreAreaDeTrabajo: String
    - descripcion: String
    - cubiculos: List<Cubiculo>
}

class Cubiculo {
    - codigo: String
    - nombre: String
    - estado: String
    - area: AreaDeTrabajo
    - vehiculo: Vehiculo
    - productos: List<Producto>
    - servicios: List<Servicio>
}


abstract class Documento {
    - codigo: String
    - estado: String
    - fechaEmision: Date
}

class Cotizacion {
    - fechaExpiracion: Date
    - tiempoMaxEntrega: int
    - proveedor: Proveedor
    - estado: String
    - detalles: List<DetalleCotizacion>
}

class DetalleCotizacion {
    - consecutivo: int
    - producto: Producto
    - tiempoGarantia: int
    - precioUnitario: double
    - descuento: double
    - iva: double
    - precioConIVA: double
    - precioConIVADescuento: double
}

class Pedido {
    - fechaMaximaEntrega: Date
    - detalles: List<DetallePedido>
}

class DetallePedido {
    - producto: Producto
    - cantidadRecibida: int
    - verificado: boolean
}

class NotaCorrecion {
    - fechaMaximaConfirmacion: Date
    - fechaMaximaEntrega: Date
    - codigoPedido: String
    - empresa: Empresa
    - proveedor: Proveedor
    - detalles: List<DetalleNotaCorrecion>
}

class DetalleNotaCorrecion {
    - producto: Producto
    - marca: String
    - nombre: String
    - precioUnitario: double
    - iva: double
    - precioUnitarioIVA: double
    - unidades: int
    - precioTotalIVA: double
    - descuento: double
    - precioTotalIVADescuento: double
    - precioErrado: double
    - diferenciaPrecio: double
    - unidadesErradas: int
    - diferenciaUnidades: int
    - descuentoErrado: double
    - diferenciaDescuento: double
    - precioTotalDiferencia: double
}

class ComprobantePago {
    - codigoTransaccion: String
    - fechaPago: Date
    - empresa: Empresa
    - proveedor: Proveedor
    - informacionPago: InformacionPago
    - valorPagar: double
    - cuentaBancariaEmpresa: CuentaBancaria
}

class OrdenVenta {
    - fechaSolicitud: Date
    - empresa: Empresa
    - cliente: Cliente
    - funcionario: Empleado
    - detallesProductos: List<DetalleVentaProducto>
    - detallesServicios: List<DetalleVentaServicio>
}

class DetalleVentaProducto {
    - producto: Producto
    - cantidad: int
    - precioUnitario: double
    - iva: double
    - descuento: double
    - precioTotal: double
}

class DetalleVentaServicio {
    - servicio: Servicio
    - descripcion: String
    - fechaInicio: Date
    - fechaFinal: Date
    - empleadoEncargado: Empleado
    - precioUnitario: double
    - iva: double
    - descuento: double
    - precioTotal: double
}





Persona --> TipoID

Empleado <|-- Supervisor
Empleado "1" -- "*" Contrato
Empleado "*" -- "*" Cargo
Empleado "*" -- "*" Documento
Empleado "*" -- "*" OrdenVenta : genera
Empleado "*" -- "*" Cotizacion : genera
Empleado "*" -- "*" Pedido : genera
Empleado "*" -- "*" NotaCorrecion : genera

Cliente "1" -- "*" Vehiculo
Cliente "*" -- "*" OrdenVenta

Empresa "1" -- "*" Empleado
Empresa "1" -- "*" Categoria
Empresa "1" -- "*" Proveedor
Empresa "1" -- "*" AreaDeTrabajo
Empresa "1" -- "*" Documento
Empresa "1" -- "*" Bodega
Empresa "1" -- "*" ComprobantePago
Empresa "1" -- "1" InformacionPago

Proveedor "*" -- "*" Producto
Proveedor "1" -- "*" Cotizacion
Proveedor "1" -- "*" NotaCorrecion
Proveedor "1" -- "*" ComprobantePago
Proveedor "1" -- "1" InformacionPago


Categoria "1" -- "*" Producto
Categoria "1" -- "*" Servicio

Catalogo "1" -- "*" Producto
Catalogo "1" -- "*" Servicio

Producto "*" -- "*" DetalleCotizacion
Producto "*" -- "*" DetallePedido
Producto "*" -- "*" DetalleVentaProducto
Producto "*" -- "*" Bodega

Servicio "*" -- "*" DetalleVentaServicio

Cotizacion "1" -- "*" DetalleCotizacion
Pedido "1" -- "*" DetallePedido
Pedido "1" -- "*" NotaCorrecion: en caso de dar al un pedido 
NotaCorrecion "1" -- "*" DetalleNotaCorrecion
OrdenVenta "1" -- "*" DetalleVentaProducto
OrdenVenta "1" -- "*" DetalleVentaServicio

AreaDeTrabajo "1" -- "*" Cubiculo
Cubiculo "1" -- "*" Servicio
Cubiculo "1" -- "*" Producto

Vehiculo "*" -- "*" Servicio

InformacionPago "1" -- "*" CuentaBancaria
InformacionPago "1" -- "1" MetodoPago

ComprobantePago "1" -- "1" Pedido

@enduml